---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/bgitibigital/public_html/
            - /bin/cp index.html $DEPLOYPATH
            - /bin/cp favicon.ico $DEPLOYPATH
            - /bin/cp -R js $DEPLOYPATH
            - /bin/cp -R css $DEPLOYPATH
            - /bin/cp -R img $DEPLOYPATH